spring.application.name=SentinelDGA

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.wvlkqigtpughybwxvapy
spring.datasource.password=TN2YYqRxCqMRmM70
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

server.port=8080